# Generated by Django 5.2 on 2025-04-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='races',
            field=models.ManyToManyField(blank=True, related_name='drivers_registered', to='racing_app.race'),
        ),
    ]
